INSERT INTO articles (
    id, title, description, created_at, href, category, 
    author_name, author_role, author_image_url, author_href
) VALUES
(2, 'Nexus: Redefining Tech with Open Innovation',
 'Nexus redefines tech through open innovation and ethical design. It empowers developers with secure, accessible solutions for modern challenges.',
 '2023-06-15 09:00:00', '#', 'Technology', 'Alice Morgan', 'Founder & Visionary',
 'https://images.unsplash.com/photo-1494790108377-be9c29b29330', '#'),
(3, 'Introducing Solstice: The Future of Nexus Wallet',
 'Solstice is the next step in digital identity. It delivers secure, user-friendly wallet functionality while ensuring privacy and seamless integration.',
 '2023-06-14 13:30:00', '#', 'Security', 'Raj Patel', 'System Architect',
 'https://images.unsplash.com/photo-1544005313-94ddf0286df2', '#'),
(4, 'How Nexus Ensures Hardware-Level Security',
 'Nexus uses advanced chips and tamper-proof methods to secure authentication. Its hardware-level measures protect data integrity and guard against modern threats.',
 '2023-06-13 11:00:00', '#', 'Hardware', 'Lena Chen', 'Embedded Engineer',
 'https://images.unsplash.com/photo-1581090700227-1e8e29f145af', '#'),
(5, 'The Nexus Learning Revolution: Open Education for All',
 'Nexus Learning offers accessible open-source tools to empower users with practical tech skills. Its resources foster innovation and real-world problem solving.',
 '2023-06-12 10:00:00', '#', 'Education', 'Omar Khalid', 'Learning Architect',
 'https://images.unsplash.com/photo-1590080877031-7011b8c7ab64', '#'),
(6, 'The Design Philosophy Behind Nexus',
 'Nexus emphasizes clean, intuitive design that balances aesthetics with usability. Its approach makes technology more accessible and enjoyable for every user.',
 '2023-06-11 15:30:00', '#', 'Design', 'Sophia Ruiz', 'Lead Designer',
 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e', '#'),
(7, 'Inside the Nexus Open Source Stack',
 'Nexus’s open-source stack promotes collaboration and transparency. It uses modern frameworks to build scalable, secure digital solutions that developers love.',
 '2023-06-10 17:15:00', '#', 'Development', 'Daniel Reed', 'Full-Stack Engineer',
 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c', '#'),
(8, 'Why Nexus Rejects Vendor Lock-In',
 'By adopting open standards and modular design, Nexus avoids vendor lock-in. This ensures users retain full control and flexibility over their technology solutions.',
 '2023-06-09 12:20:00', '#', 'Philosophy', 'Victor Zhang', 'Tech Ethicist',
 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce', '#'),
(9, 'What Makes Nexus Unique?',
 'Nexus uniquely blends security, design, and open-source principles into one ecosystem. It empowers innovation while putting full control and transparency into users’ hands.',
 '2023-06-08 14:10:00', '#', 'Innovation', 'Meera Sinha', 'Systems Lead',
 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39', '#');
